CREATE TABLE merchants (
 id UUID PRIMARY KEY,
 profile JSONB NOT NULL,
 token_hash TEXT NOT NULL UNIQUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
