server {
 listen 80;
 server_name _;
 resolver 127.0.0.11 valid=10s ipv6=off;
 add_header X-Content-Type-Options nosniff always;
 add_header Referrer-Policy strict-origin-when-cross-origin always;
 location = /health { access_log off; default_type text/plain; return 200 'ok'; }
 location = /graphql { set $api api-gateway:80; proxy_pass http://$api; proxy_connect_timeout 5s; proxy_read_timeout 35s; }
 location /mfe/signup/ { set $signup signup:80; rewrite ^/mfe/signup/(.*)$ /$1 break; proxy_pass http://$signup; }
 location /mfe/orders/ { set $orders orders:80; rewrite ^/mfe/orders/(.*)$ /$1 break; proxy_pass http://$orders; }
 location /mfe/checkout/ { set $checkout checkout:80; rewrite ^/mfe/checkout/(.*)$ /$1 break; proxy_pass http://$checkout; }
 location / { set $shell shell:80; proxy_pass http://$shell; }
}
